apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sshd
  labels:
    app: sshd
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sshd
    spec:
      containers:
      - image: clevandowski/centos-sshd
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp /home/guest/.ssh/authorized_keys_ /home/guest/.ssh/authorized_keys && chown guest:guest /home/guest/.ssh/authorized_keys && chmod 600 /home/guest/.ssh/authorized_keys"]
        imagePullPolicy: Always
        name: sshd
        ports:
        - containerPort: 22
          name: resanet-tp-00
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200"
        volumeMounts:
        - name: ssh-authorized-keys
          mountPath: /home/guest/.ssh/authorized_keys_
          subPath: authorized_keys_

      volumes:
      - name: ssh-authorized-keys
        configMap:
          name: sshd
          defaultMode: 0644
